server:
  port: 8080

spring:
  main:
    lazy-initialization: false

  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"

  flyway:
    url: "${spring.datasource.url}"
    user: "${spring.datasource.username}"
    password: "${spring.datasource.password}"
    validate-on-migrate: true
    enabled: true
